[project]
name = "beacons"
version = "0.1.0"
description = "A Streamlit app that visualizes Google Sheet data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit",
    "pandas",
    "st-gsheets-connection",
    "plotly"
]
